esphome:
  name: catomator
  friendly_name: Cat Laser

esp8266:
  board: d1_mini

logger:
web_server:
  port: 80
  local: true
  ota: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:
  encryption:
    key: !secret api_key

  services:
    - service: servo_y
      variables:
        level: float
      then:
        - servo.write:
            id: servo_y
            level: !lambda 'return level / 100.0;'
    - service: servo_x
      variables:
        level: float
      then:
        - servo.write:
            id: servo_x
            level: !lambda 'return level / 100.0;'

ota:
  - platform: esphome
    password: !secret ota_password
    port: 2000

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: esp8266_pwm
    id: pwm_1
    pin: D5
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_2
    pin: D6
    frequency: 50 Hz

servo:
  - id: servo_y
    output: pwm_1
    transition_length: '10s'
    auto_detach_time: 1s
  - id: servo_x
    output: pwm_2
    transition_length: '10s'
    auto_detach_time: 1s

switch:
  - platform: gpio
    pin: D7
    name: 'Laser Pointer'
    restore_mode: ALWAYS_OFF
